- name: set managed for puppet
  command: "sed -i -e 's/managed = False/managed = True/g' {{ dir }}/servermon/servermon/puppet/models.py"
- name: run syncdb
  django_manage: "command=syncdb app_path={{ dir }}/servermon/servermon"
- name: run migrate
  django_manage: "command=migrate app_path={{ dir }}/servermon/servermon"
- name: load sampledata
  django_manage: "command=loaddata app_path={{ dir }}/servermon/servermon fixtures='vendor-model sampledata'"
